# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180125_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='block_review',
            field=models.BooleanField(default=False),
        ),
    ]
