# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_block_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(default='ugvhy@hdf.ghdchg', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='dgt', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='hjv', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='jfvjiu', max_length=255),
            preserve_default=False,
        ),
    ]
