# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveIntegerField(choices=[(b'1', b'One'), (b'2', b'Tow'), (b'3', b'Three'), (b'4', b'Four'), (b'5', b'Five')]),
        ),
    ]
