# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_checkout_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
