# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_checkout_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='status',
            field=models.CharField(choices=[(b'Pending', b'pending'), (b'Accepted', b'accepted'), (b'Rejected', b'rejected')], default=b'Pending', max_length=255),
        ),
    ]
