# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180129_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='status',
            field=models.CharField(choices=[(b'waiting', b'Waiting'), (b'pending', b'Pending'), (b'accepted', b'Accepted'), (b'rejected', b'Rejected')], default=b'waiting', max_length=255),
        ),
    ]
