# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180129_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
