# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180131_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'verbose_name_plural': 'Orders'},
        ),
    ]
