# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180128_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number_of_sales',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_views',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
