# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180128_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='number_of_products',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
