# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180128_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avg_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_sales',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
