# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180128_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
