# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180128_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slider',
            field=models.BooleanField(default=False),
        ),
    ]
