# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='block_review',
            field=models.BooleanField(default=False),
        ),
    ]
